name: Salesforce CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  pmd-apex:
    runs-on: ubuntu-latest
    env:
      PMD_VERSION: 6.55.0
      PMD_HOME: $HOME/pmd-bin-${{ env.PMD_VERSION }}
      PMD_ZIP_HOME: $HOME/pmd-bin-${{ env.PMD_VERSION }}.zip
      PMD_DOWNLOAD_URL: https://github.com/pmd/pmd/releases/download/pmd_releases/${{ env.PMD_VERSION}}/pmd-bin-${{ env.PMD_VERSION }}.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

       - name: Download PMD Zip
        run: |
          echo "PMD Download URL: $PMD_DOWNLOAD_URL"
          curl -L -o $PMD_ZIP_HOME $PMD_DOWNLOAD_URL

      - name: Unzip PMD Zip
        run: |
          echo "Unzipping PMD: $PMD_ZIP_HOME"
          unzip $PMD_ZIP_HOME -d $HOME

      - name: Delete PMD Zip
        run: |
          echo "Deleting PMD Zip: $PMD_ZIP_HOME"
          rm $PMD_ZIP_HOME

      - name: Run PMD
        run: |
          $PMD_HOME/bin/run.sh pmd -d force-app -R category/apex/design.xml -f text --cache .pmd-cache

  lint-lwc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Lint Lightning Web Components
        run: npm run lint

  test-lwc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Test Lightning Web Components
        run: npm run test

  salesforce-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Authorize Dev Hub
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth_url.txt
          sf org login sfdx-url --sfdx-url-file auth_url.txt --alias DevHub --set-default-dev-hub
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}

      - name: Create Scratch Org
        run: |
          sf org create scratch --definition-file config/project-scratch-def.json --alias ci-scratch-org --set-default --duration-days 1

      - name: Push Source to Scratch Org
        run: |
          sf project deploy start --target-org ci-scratch-org

      - name: Run Apex tests on Scratch Org
        run: |
          sf apex test run --target-org ci-scratch-org --code-coverage --result-format tap --output-dir test-results --wait 10

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: apex-test-results
          path: test-results

      - name: Delete Scratch Org
        if: always()
        run: |
          sf org delete scratch --target-org ci-scratch-org --no-prompt
