name: Salesforce CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  pmd-apex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pmd/pmd-github-action@v2
        with:
          analyzeModifiedFilesOnly: false
          sourcePath: "force-app"
          rulesets: "ruleset.xml"
          createGitHubAnnotations: true
          uploadSarifReport: false

  lint-lwc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Lint Lightning Web Components
        run: npm run lint

  test-lwc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Test Lightning Web Components
        run: npm run test

  validate-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Authorize Staging Org
        run: |
          echo ${{ secrets.STAGING_SFDX_AUTH_URL }} | sf org login sfdx-url --alias Staging --sfdx-url-stdin 

      - name: Validate Against Staging Org
        run: sf project deploy validate --target-org Staging --source-dir force-app
  
  validate-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Authorize Production Org
        run: |
          echo ${{ secrets.PRODUCTION_SFDX_AUTH_URL }} | sf org login sfdx-url --alias Production --sfdx-url-stdin 

      - name: Validate Against Production Org
        run: sf project deploy validate --target-org Production --source-dir force-app