name: Deploy To Staging Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - staging

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    
  deploy-to-staging:
    name: Deploy To Staging
    uses: ./.github/workflows/deploy-to-org.yml
    secrets:
      sfdx-auth-url: ${{ secrets.STAGING_SFDX_AUTH_URL }}
