name: Deploy To Org Workflow

on:
  workflow_call:
    secrets:
      dev-hub-sfdx-auth-url:
        required: true

jobs:
  deploy-to-org:
    name: Deploy To Org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authorize Dev Hub
        run: |
          echo "${{ secrets.dev-hub-sfdx-auth-url }}" | sf org login sfdx-url --alias DevHub --sfdx-url-stdin 

      - name: Show Dev Hub Limits
        run: |
          sf org list limits --target-org DevHub

      - name: Create Scratch Org
        run: |
          sf org create scratch --alias scratch-org --duration-days 1

      - name: Push Source
        run: |
          sf project deploy start --target-org scratch-org

      - name: Run Apex Tests
        run: |
          sf apex test run \
            --target-org scratch-org \
            --code-coverage \
            --detailed-coverage \
            --result-format human \
            --synchronous

      - name: Delete Scratch Org
        if: always()
        run: |
          sf org delete scratch --target-org scratch-org --no-prompt