name: Deploy To Production Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - production

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    
  deploy-to-production:
    name: Deploy To Production
    needs: ci
    uses: ./.github/workflows/deploy-to-org.yml
    secrets:
      sfdx-auth-url: ${{ secrets.PRODUCTION_SFDX_AUTH_URL }}
