name: Deploy To Production Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy-to-production:
    uses: ./.github/workflows/deploy-to-org.yml
    secrets:
      sfdx-auth-url: ${{ secrets.PRODUCTION_SFDX_AUTH_URL }}
