name: Feature CI Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - production
      - staging

jobs:
    ci:
      uses: ./.github/workflows/ci.yml