name: Nightly CI Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  deploy-to-scratch-org:
    name: Deploy To Scratch Org
    uses: ./.github/workflows/deploy-to-scratch-org.yml
    secrets:
      dev-hub-sfdx-auth-url: ${{ secrets.DEV_HUB_SFDX_AUTH_URL }}
      

    