name: Production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: 
      - main

jobs:
  validate:
    name: Validate Against Production
    uses: ./.github/workflows/validate-against-org.yml
    secrets:
      sfdx-auth-url: ${{ secrets.PRODUCTION_SFDX_AUTH_URL }}
