name: Staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - staging

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Against Staging
        uses: ./.github/actions/validate-against-org
        with: 
          sfdx-auth-url: ${{ secrets.STAGING_SFDX_AUTH_URL }}
