name: Staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - staging

jobs:
  validate:
    - name: Validate Against Staging
      uses: ./.github/workflows/validate-against-org.yml
      secrets: 
        sfdx-auth-url: ${{ secrets.STAGING_SFDX_AUTH_URL }}
